# Generated by Django 5.1 on 2024-08-25 17:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('citybreaks', 'City breaks'), ('corporate', 'Corporate'), ('cultural', 'Cultural'), ('general', 'General'), ('holidays', 'Holidays')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('ratings', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)])),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='trip_app.journey')),
            ],
        ),
    ]
